name: modelprediction
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - streamlit
  - pandas
  - numpy
  - openpyxl
  - xlrd
  - scikit-learn  # Most ML models saved as pickle are from scikit-learn
  - xgboost  # Optional: in case you load XGBoost models
  - lightgbm # Optional: in case you load LightGBM models